project:
  type: website

website:
  title: "NUMBAT Hacky Hour"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Schedule
        href: schedule.qmd
      - text: Activiy
        menu: 
          - text: Kick Off
            file: kick-off.qmd
          - text: Quarto Craft
            file: quarto-craft.qmd
          - text: Package Design Feedback
            file: package-design-session01.qmd
      - text: News
        href: news.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
filters:
  - shinylive



